networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:

services:
  symfony:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_frankenphp_app
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
      - '8443:443/udp'
    volumes:
      - ./backend:/app
    networks:
      - symfony_net
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 1.5G
    environment:
      FRANKENPHP_CONFIG: |
        worker {
          file /app/public/index.php
          watch /app
        }
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1']
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgis/postgis:16-3.4
    container_name: symfony_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_net
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

  mailer:
    image: axllent/mailpit
    container_name: symfony_mailer
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - symfony_net