<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260108105422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, format VARCHAR(255) NOT NULL, entry_cost VARCHAR(255) NOT NULL, description TEXT NOT NULL, number_participants INT NOT NULL, start_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, slug VARCHAR(180) NOT NULL, game_id INT NOT NULL, shop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3BAE0AA7989D9B62 ON event (slug)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7E48FD905 ON event (game_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA74D16C4DD ON event (shop_id)');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, alt VARCHAR(255) DEFAULT NULL, position INT NOT NULL, shop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C53D045F4D16C4DD ON image (shop_id)');
        $this->addSql('CREATE TABLE participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, unregister_token VARCHAR(64) NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D79F6B11BE4764C8 ON participant (unregister_token)');
        $this->addSql('CREATE INDEX IDX_D79F6B1171F7E88B ON participant (event_id)');
        $this->addSql('CREATE TABLE shop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, address VARCHAR(150) NOT NULL, zipcode INT NOT NULL, city VARCHAR(80) NOT NULL, state VARCHAR(40) NOT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, opening_hours TEXT DEFAULT NULL, longitude DOUBLE PRECISION NOT NULL, latitude DOUBLE PRECISION NOT NULL, slug VARCHAR(180) NOT NULL, selling BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, description TEXT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC6A4CA2A76ED395 ON shop (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_SLUG ON shop (slug)');
        $this->addSql('CREATE TABLE shop_game (shop_id INT NOT NULL, game_id INT NOT NULL, PRIMARY KEY (shop_id, game_id))');
        $this->addSql('CREATE INDEX IDX_E2D9D7F74D16C4DD ON shop_game (shop_id)');
        $this->addSql('CREATE INDEX IDX_E2D9D7F7E48FD905 ON shop_game (game_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (email)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA74D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F4D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B1171F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shop ADD CONSTRAINT FK_AC6A4CA2A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shop_game ADD CONSTRAINT FK_E2D9D7F74D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shop_game ADD CONSTRAINT FK_E2D9D7F7E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7E48FD905');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA74D16C4DD');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F4D16C4DD');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B1171F7E88B');
        $this->addSql('ALTER TABLE shop DROP CONSTRAINT FK_AC6A4CA2A76ED395');
        $this->addSql('ALTER TABLE shop_game DROP CONSTRAINT FK_E2D9D7F74D16C4DD');
        $this->addSql('ALTER TABLE shop_game DROP CONSTRAINT FK_E2D9D7F7E48FD905');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE participant');
        $this->addSql('DROP TABLE shop');
        $this->addSql('DROP TABLE shop_game');
        $this->addSql('DROP TABLE "users"');
    }
}
